# Generated by Django 3.2.8 on 2021-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_places_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(max_length=400, verbose_name='Краткое описание'),
        ),
    ]
