# Generated by Django 3.2.8 on 2021-10-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20211005_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='json_path',
            field=models.FilePathField(default=False, path='../static/places', verbose_name='Адрес json файла'),
            preserve_default=False,
        ),
    ]
